-- ==========================================================================
-- LMS SEED DATA SEGMENT: Categories, Tags, Books, BookCategories, BookTags, BookCopies
-- Auto-generated by splitting tool
-- ==========================================================================

INSERT INTO SystemConfigurations (configKey, configValue, description)
VALUES ('GEMINI_API_KEY', 'YOUR_GEMINI_API_KEY', 'API Key cho Google Gemini AI Recommendation');



-- ------------------------------------------------------------
-- 1. CLEANUP OLD TEST DATA
-- ------------------------------------------------------------
-- ------------------------------------------------------------
-- 2. INSERT CATEGORIES (6 CATEGORIES)
-- ------------------------------------------------------------

INSERT INTO Category (categoryId, name, description) VALUES 
(1, 'Programming Languages', 'Sách về các ngôn ngữ lập trình phổ biến'),
(2, 'Software Architecture', 'Sách về thiết kế kiến trúc và mẫu thiết kế phần mềm'),
(3, 'Databases & SQL', 'Sách về cơ sở dữ liệu quan hệ, NoSQL và SQL tối ưu'),
(4, 'Web Development', 'Sách phát triển giao diện và ứng dụng web (React, Node, JS)'),
(5, 'DevOps & Cloud', 'Sách về điện toán đám mây, Docker, Kubernetes và CI/CD'),
(6, 'AI & Data Science', 'Sách về Trí tuệ nhân tạo, Machine Learning và Khoa học dữ liệu');

-- ------------------------------------------------------------
-- 3. INSERT TAGS (15 TAGS)
-- ------------------------------------------------------------

INSERT INTO Tag (tagId, name) VALUES 
(1, 'Java'),
(2, 'Python'),
(3, 'Go'),
(4, 'C++'),
(5, 'JavaScript'),
(6, 'React'),
(7, 'Node.js'),
(8, 'Architecture'),
(9, 'Design Patterns'),
(10, 'Microservices'),
(11, 'SQL'),
(12, 'NoSQL'),
(13, 'Docker & Kubernetes'),
(14, 'Cloud Native'),
(15, 'Machine Learning');

-- ------------------------------------------------------------
-- 4. INSERT BOOKS (75 BOOKS)
-- ------------------------------------------------------------

INSERT INTO Book (bookId, isbn, title, author, publisher, publicationYear, price, totalQuantity, availableQuantity, status) VALUES 
-- Category 1: Programming Languages (1-8, 46-48)
(1, '978-0134685991', 'Effective Java', 'Joshua Bloch', 'Addison-Wesley', 2017, 45.00, 2, 2, 'available'),
(2, '978-0596009205', 'Head First Java', 'Kathy Sierra', 'O''Reilly Media', 2005, 30.00, 2, 2, 'available'),
(3, '978-1449331818', 'Learning Python', 'Mark Lutz', 'O''Reilly Media', 2013, 55.00, 2, 2, 'available'),
(4, '978-1491946008', 'Fluent Python', 'Luciano Ramalho', 'O''Reilly Media', 2015, 60.00, 2, 2, 'available'),
(5, '978-1453916701', 'The Go Programming Language', 'Alan A. A. Donovan', 'Addison-Wesley', 2015, 49.00, 2, 2, 'available'),
(6, '978-1449311605', 'Programming in Go', 'Mark Summerfield', 'Addison-Wesley', 2012, 45.00, 2, 2, 'available'),
(7, '978-0321714114', 'C++ Primer', 'Stanley B. Lippman', 'Addison-Wesley', 2012, 50.00, 2, 2, 'available'),
(8, '978-0131103627', 'The C Programming Language', 'Brian W. Kernighan', 'Prentice Hall', 1988, 40.00, 2, 2, 'available'),

-- Category 2: Software Architecture (9-16, 49-51)
(9, '978-0134494166', 'Clean Architecture', 'Robert C. Martin', 'Prentice Hall', 2017, 42.00, 2, 2, 'available'),
(10, '978-0321125217', 'Domain-Driven Design', 'Eric Evans', 'Addison-Wesley', 2003, 50.00, 2, 2, 'available'),
(11, '978-0201633610', 'Design Patterns', 'Erich Gamma', 'Addison-Wesley', 1994, 55.00, 2, 2, 'available'),
(12, '978-1491956250', 'Building Microservices', 'Sam Newman', 'O''Reilly Media', 2015, 48.00, 2, 2, 'available'),
(13, '978-1617294549', 'Microservices Patterns', 'Chris Richardson', 'Manning', 2018, 52.00, 2, 2, 'available'),
(14, '978-1449373320', 'Designing Data-Intensive Applications', 'Martin Kleppmann', 'O''Reilly Media', 2017, 48.00, 2, 2, 'available'),
(15, '978-1492056812', 'Fundamentals of Software Architecture', 'Mark Richards', 'O''Reilly Media', 2020, 55.00, 2, 2, 'available'),
(16, '978-0321127426', 'Patterns of Enterprise Application Architecture', 'Martin Fowler', 'Addison-Wesley', 2002, 58.00, 2, 2, 'available'),

-- Category 3: Databases & SQL (17-24, 52-54)
(17, '978-0134858333', 'SQL Queries for Mere Mortals', 'John L. Viescas', 'Addison-Wesley', 2018, 40.00, 2, 2, 'available'),
(18, '978-1449314286', 'High Performance MySQL', 'Baron Schwartz', 'O''Reilly Media', 2012, 45.00, 2, 2, 'available'),
(19, '978-1491954461', 'MongoDB: The Definitive Guide', 'Shannon Bradshaw', 'O''Reilly Media', 2019, 46.00, 2, 2, 'available'),
(20, '978-1449310301', 'NoSQL Distilled', 'Pramod J. Sadalage', 'Addison-Wesley', 2012, 38.00, 2, 2, 'available'),
(21, '978-1492057611', 'Learning SQL', 'Alan Beaulieu', 'O''Reilly Media', 2020, 39.00, 2, 2, 'available'),
(22, '978-1492004738', 'SQL Cookbook', 'Anthony Molinaro', 'O''Reilly Media', 2020, 48.00, 2, 2, 'available'),
(23, '978-1449309398', 'Seven Databases in Seven Weeks', 'Eric Redmond', 'Pragmatic Bookshelf', 2012, 40.00, 2, 2, 'available'),
(24, '978-0073523323', 'Database System Concepts', 'Abraham Silberschatz', 'McGraw-Hill', 2010, 75.00, 2, 2, 'available'),

-- Category 4: Web Development (25-32, 55-57)
(25, '978-0596517748', 'JavaScript: The Good Parts', 'Douglas Crockford', 'O''Reilly Media', 2008, 25.00, 2, 2, 'available'),
(26, '978-1492054375', 'You Don''t Know JS Yet', 'Kyle Simpson', 'O''Reilly Media', 2020, 30.00, 2, 2, 'available'),
(27, '978-1732329393', 'Eloquent JavaScript', 'Marijn Haverbeke', 'No Starch Press', 2018, 35.00, 2, 2, 'available'),
(28, '978-1492082904', 'Learning React', 'Alex Banks', 'O''Reilly Media', 2020, 45.00, 2, 2, 'available'),
(29, '978-1484254585', 'Pro React 16', 'Adam Freeman', 'Apress', 2019, 49.00, 2, 2, 'available'),
(30, '978-1839214110', 'Node.js Design Patterns', 'Mario Casciaro', 'Packt', 2020, 50.00, 2, 2, 'available'),
(31, '978-1492053514', 'Web Development with Node and Express', 'Ethan Brown', 'O''Reilly Media', 2019, 42.00, 2, 2, 'available'),
(32, '978-1543997675', 'Beginning Node.js, Express & MongoDB', 'Greg Lim', 'Greg Lim Publishing', 2020, 25.00, 2, 2, 'available'),

-- Category 5: DevOps & Cloud (33-39, 58-60)
(33, '978-1942788003', 'The DevOps Handbook', 'Gene Kim', 'IT Revolution Press', 2016, 45.00, 2, 2, 'available'),
(34, '978-1916585126', 'Docker Deep Dive', 'Nigel Poulton', 'Nigel Poulton Publishing', 2020, 38.00, 2, 2, 'available'),
(35, '978-1492003290', 'Kubernetes Up and Running', 'Kelsey Hightower', 'O''Reilly Media', 2019, 45.00, 2, 2, 'available'),
(36, '978-1119504221', 'AWS Certified Solutions Architect Study Guide', 'Ben Piper', 'Sybex', 2019, 50.00, 2, 2, 'available'),
(37, '978-1617294006', 'Cloud Native Patterns', 'Cornelia Davis', 'Manning', 2019, 47.00, 2, 2, 'available'),
(38, '978-1492046905', 'Terraform: Up & Running', 'Yevgeniy Brikman', 'O''Reilly Media', 2019, 45.00, 2, 2, 'available'),
(39, '978-1491929124', 'Site Reliability Engineering', 'Betsy Beyer', 'O''Reilly Media', 2016, 49.00, 2, 2, 'available'),

-- Category 6: AI & Data Science (40-45, 61-75)
(40, '978-1492032649', 'Hands-On Machine Learning', 'Aurélien Géron', 'O''Reilly Media', 2019, 65.00, 2, 2, 'available'),
(41, '978-1491957660', 'Python for Data Analysis', 'Wes McKinney', 'O''Reilly Media', 2017, 50.00, 2, 2, 'available'),
(42, '978-1492041139', 'Data Science from Scratch', 'Joel Grus', 'O''Reilly Media', 2019, 40.00, 2, 2, 'available'),
(43, '978-1492051053', 'Introduction to Machine Learning with Python', 'Andreas C. Müller', 'O''Reilly Media', 2020, 48.00, 2, 2, 'available'),
(44, '978-1462935513', 'Deep Learning', 'Ian Goodfellow', 'MIT Press', 2016, 80.00, 2, 2, 'available'),
(45, '978-1108488051', 'Mathematics for Machine Learning', 'Marc Peter Deisenroth', 'Cambridge University Press', 2020, 55.00, 2, 2, 'available'),

-- Category 1 (Added)
(46, '978-0135111529', 'Core Java Volume I--Fundamentals', 'Cay S. Horstmann', 'Pearson', 2018, 48.00, 2, 2, 'available'),
(47, '978-0321334879', 'Effective C++', 'Scott Meyers', 'Addison-Wesley', 2005, 45.00, 2, 2, 'available'),
(48, '978-0131872486', 'Thinking in Java', 'Bruce Eckel', 'Prentice Hall', 2006, 50.00, 2, 2, 'available'),

-- Category 2 (Added)
(49, '978-1492086895', 'Software Architecture: The Hard Parts', 'Neal Ford', 'O''Reilly Media', 2021, 54.00, 2, 2, 'available'),
(50, '978-0321200686', 'Enterprise Integration Patterns', 'Gregor Hohpe', 'Addison-Wesley', 2003, 58.00, 2, 2, 'available'),
(51, '978-1736049112', 'System Design Interview', 'Alex Xu', 'ByteByteGo', 2020, 39.00, 2, 2, 'available'),

-- Category 3 (Added)
(52, '978-1540801821', 'SQL Practice Problems', 'Sylvia Moestl Vasilik', 'Independently Published', 2016, 20.00, 2, 2, 'available'),
(53, '978-0134023212', 'NoSQL for Mere Mortals', 'Dan Sullivan', 'Addison-Wesley', 2015, 42.00, 2, 2, 'available'),
(54, '978-3950307825', 'SQL Performance Explained', 'Markus Winand', 'Markus Winand', 2012, 35.00, 2, 2, 'available'),

-- Category 4 (Added)
(55, '978-1118008188', 'HTML and CSS: Design and Build Websites', 'Jon Duckett', 'Wiley', 2011, 29.00, 2, 2, 'available'),
(56, '978-1803234502', 'React Key Concepts', 'Maximilian Schwarzmüller', 'Packt', 2022, 38.00, 2, 2, 'available'),
(57, '978-1838987589', 'Node.js Web Development', 'David Herron', 'Packt', 2020, 44.00, 2, 2, 'available'),

-- Category 5 (Added)
(58, '978-1491979440', 'Kubernetes Cookbook', 'Sébastien Goasguen', 'O''Reilly Media', 2018, 46.00, 2, 2, 'available'),
(59, '978-1492029420', 'Implementing Service Quality', 'SRE Team', 'O''Reilly Media', 2019, 45.00, 2, 2, 'available'),
(60, '978-1119756163', 'AWS Certified Cloud Practitioner', 'CLF', 'Sybex', 2021, 30.00, 2, 2, 'available'),

-- Category 6 (Added)
(61, '978-1466575577', 'Introduction to Probability', 'Joseph K. Blitzstein', 'Chapman and Hall/CRC', 2019, 75.00, 2, 2, 'available'),
(62, '978-0387310732', 'Pattern Recognition and Machine Learning', 'Christopher M. Bishop', 'Springer', 2006, 95.00, 2, 2, 'available'),
(63, '978-0986001002', 'Neural Networks and Deep Learning', 'Michael Nielsen', 'Determination Press', 2015, 30.00, 2, 2, 'available'),
(64, '978-1491907337', 'Think Stats', 'Allen B. Downey', 'O''Reilly Media', 2014, 35.00, 2, 2, 'available'),
(65, '978-1491912058', 'Python Data Science Handbook', 'Jake VanderPlas', 'O''Reilly Media', 2016, 55.00, 2, 2, 'available'),
(66, '978-1617294433', 'Deep Learning with Python', 'François Chollet', 'Manning', 2017, 50.00, 2, 2, 'available'),
(67, '978-1098103248', 'Natural Language Processing with Transformers', 'Lewis Tunstall', 'O''Reilly Media', 2022, 58.00, 2, 2, 'available'),
(68, '978-0262039245', 'Reinforcement Learning', 'Richard S. Sutton', 'MIT Press', 2018, 90.00, 2, 2, 'available'),
(69, '978-1800563452', 'Hands-On Data Analysis with Pandas', 'Stefanie Molin', 'Packt', 2021, 40.00, 2, 2, 'available'),
(70, '978-1491953242', 'Feature Engineering for Machine Learning', 'Alice Zheng', 'O''Reilly Media', 2018, 38.00, 2, 2, 'available'),
(71, '978-0486832869', 'Introduction to Artificial Intelligence', 'Philip C Jackson', 'Dover Publications', 2019, 18.00, 2, 2, 'available'),
(72, '978-0134610993', 'Artificial Intelligence: A Modern Approach', 'Stuart Russell', 'Pearson', 2020, 120.00, 2, 2, 'available'),
(73, '978-1492072942', 'Practical Statistics for Data Scientists', 'Peter Bruce', 'O''Reilly Media', 2020, 42.00, 2, 2, 'available'),
(74, '978-1492079361', 'Data Science on AWS', 'Chris Fregly', 'O''Reilly Media', 2021, 58.00, 2, 2, 'available'),
(75, '978-1098115784', 'Machine Learning Design Patterns', 'Lakshmanan', 'O''Reilly Media', 2021, 55.00, 2, 2, 'available');

-- ------------------------------------------------------------
-- 5. INSERT BOOK CATEGORIES (75 BOOKS)
-- ------------------------------------------------------------
INSERT INTO BookCategory (bookId, categoryId) VALUES 
(1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1),
(9, 2), (10, 2), (11, 2), (12, 2), (13, 2), (14, 2), (15, 2), (16, 2),
(17, 3), (18, 3), (19, 3), (20, 3), (21, 3), (22, 3), (23, 3), (24, 3),
(25, 4), (26, 4), (27, 4), (28, 4), (29, 4), (30, 4), (31, 4), (32, 4),
(33, 5), (34, 5), (35, 5), (36, 5), (37, 5), (38, 5), (39, 5),
(40, 6), (41, 6), (42, 6), (43, 6), (44, 6), (45, 6),
(46, 1), (47, 1), (48, 1),
(49, 2), (50, 2), (51, 2),
(52, 3), (53, 3), (54, 3),
(55, 4), (56, 4), (57, 4),
(58, 5), (59, 5), (60, 5),
(61, 6), (62, 6), (63, 6), (64, 6), (65, 6), (66, 6), (67, 6), (68, 6), (69, 6), (70, 6), (71, 6), (72, 6), (73, 6), (74, 6), (75, 6);

-- ------------------------------------------------------------
-- 6. INSERT BOOK TAGS
-- ------------------------------------------------------------
INSERT INTO BookTag (bookId, tagId) VALUES 
-- Programming Languages
(1, 1), (1, 9),
(2, 1),
(3, 2),
(4, 2),
(5, 3),
(6, 3),
(7, 4),
(8, 4),
-- Software Architecture
(9, 8), (9, 9),
(10, 8), (10, 9),
(11, 9),
(12, 10), (12, 14),
(13, 10), (13, 9),
(14, 8), (14, 10),
(15, 8),
(16, 8), (16, 9),
-- Databases & SQL
(17, 11),
(18, 11),
(19, 12),
(20, 12),
(21, 11),
(22, 11),
(23, 11), (23, 12),
(24, 11),
-- Web Development
(25, 5),
(26, 5),
(27, 5),
(28, 6), (28, 5),
(29, 6),
(30, 7), (30, 9),
(31, 7), (31, 5),
(32, 7), (32, 12),
-- DevOps & Cloud
(33, 14),
(34, 13),
(35, 13), (35, 14),
(36, 14),
(37, 14), (37, 10),
(38, 14),
(39, 14),
-- AI & Data Science
(40, 15), (40, 2),
(41, 2),
(42, 15), (42, 2),
(43, 15), (43, 2),
(44, 15),
(45, 15),
-- Added Books Tags
(46, 1),
(47, 4),
(48, 1), (48, 9),
(49, 8), (49, 10),
(50, 8), (50, 9),
(51, 8),
(52, 11),
(53, 12),
(54, 11),
(55, 5),
(56, 6), (56, 5),
(57, 7), (57, 5),
(58, 13), (58, 14),
(59, 14),
(60, 14),
(61, 15),
(62, 15),
(63, 15),
(64, 2),
(65, 2), (65, 15),
(66, 2), (66, 15),
(67, 15), (67, 2),
(68, 15),
(69, 2), (69, 11),
(70, 15), (70, 2),
(71, 15),
(72, 15),
(73, 2),
(74, 14), (74, 15),
(75, 15), (75, 9);

-- ------------------------------------------------------------
-- 7. INSERT BOOK COPIES (75 BOOKS * 2 COPIES = 150 COPIES)
-- ------------------------------------------------------------

INSERT INTO BookCopy (bookCopyId, bookId, barcode, condition, status) VALUES 
(1, 1, 'BC-001-1', 'good', 'available'), (2, 1, 'BC-001-2', 'good', 'available'),
(3, 2, 'BC-002-1', 'good', 'available'), (4, 2, 'BC-002-2', 'good', 'available'),
(5, 3, 'BC-003-1', 'good', 'available'), (6, 3, 'BC-003-2', 'good', 'available'),
(7, 4, 'BC-004-1', 'good', 'available'), (8, 4, 'BC-004-2', 'good', 'available'),
(9, 5, 'BC-005-1', 'good', 'available'), (10, 5, 'BC-005-2', 'good', 'available'),
(11, 6, 'BC-006-1', 'good', 'available'), (12, 6, 'BC-006-2', 'good', 'available'),
(13, 7, 'BC-007-1', 'good', 'available'), (14, 7, 'BC-007-2', 'good', 'available'),
(15, 8, 'BC-008-1', 'good', 'available'), (16, 8, 'BC-008-2', 'good', 'available'),
(17, 9, 'BC-009-1', 'good', 'available'), (18, 9, 'BC-009-2', 'good', 'available'),
(19, 10, 'BC-010-1', 'good', 'available'), (20, 10, 'BC-010-2', 'good', 'available'),
(21, 11, 'BC-011-1', 'good', 'available'), (22, 11, 'BC-011-2', 'good', 'available'),
(23, 12, 'BC-012-1', 'good', 'available'), (24, 12, 'BC-012-2', 'good', 'available'),
(25, 13, 'BC-013-1', 'good', 'available'), (26, 13, 'BC-013-2', 'good', 'available'),
(27, 14, 'BC-014-1', 'good', 'available'), (28, 14, 'BC-014-2', 'good', 'available'),
(29, 15, 'BC-015-1', 'good', 'available'), (30, 15, 'BC-015-2', 'good', 'available'),
(31, 16, 'BC-016-1', 'good', 'available'), (32, 16, 'BC-016-2', 'good', 'available'),
(33, 17, 'BC-017-1', 'good', 'available'), (34, 17, 'BC-017-2', 'good', 'available'),
(35, 18, 'BC-018-1', 'good', 'available'), (36, 18, 'BC-018-2', 'good', 'available'),
(37, 19, 'BC-019-1', 'good', 'available'), (38, 19, 'BC-019-2', 'good', 'available'),
(39, 20, 'BC-020-1', 'good', 'available'), (40, 20, 'BC-020-2', 'good', 'available'),
(41, 21, 'BC-021-1', 'good', 'available'), (42, 21, 'BC-021-2', 'good', 'available'),
(43, 22, 'BC-022-1', 'good', 'available'), (44, 22, 'BC-022-2', 'good', 'available'),
(45, 23, 'BC-023-1', 'good', 'available'), (46, 23, 'BC-023-2', 'good', 'available'),
(47, 24, 'BC-024-1', 'good', 'available'), (48, 24, 'BC-024-2', 'good', 'available'),
(49, 25, 'BC-025-1', 'good', 'available'), (50, 25, 'BC-025-2', 'good', 'available'),
(51, 26, 'BC-026-1', 'good', 'available'), (52, 26, 'BC-026-2', 'good', 'available'),
(53, 27, 'BC-027-1', 'good', 'available'), (54, 27, 'BC-027-2', 'good', 'available'),
(55, 28, 'BC-028-1', 'good', 'available'), (56, 28, 'BC-028-2', 'good', 'available'),
(57, 29, 'BC-029-1', 'good', 'available'), (58, 29, 'BC-029-2', 'good', 'available'),
(59, 30, 'BC-030-1', 'good', 'available'), (60, 30, 'BC-030-2', 'good', 'available'),
(61, 31, 'BC-031-1', 'good', 'available'), (62, 31, 'BC-031-2', 'good', 'available'),
(63, 32, 'BC-032-1', 'good', 'available'), (64, 32, 'BC-032-2', 'good', 'available'),
(65, 33, 'BC-033-1', 'good', 'available'), (66, 33, 'BC-033-2', 'good', 'available'),
(67, 34, 'BC-034-1', 'good', 'available'), (68, 34, 'BC-034-2', 'good', 'available'),
(69, 35, 'BC-035-1', 'good', 'available'), (70, 35, 'BC-035-2', 'good', 'available'),
(71, 36, 'BC-036-1', 'good', 'available'), (72, 36, 'BC-036-2', 'good', 'available'),
(73, 37, 'BC-037-1', 'good', 'available'), (74, 37, 'BC-037-2', 'good', 'available'),
(75, 38, 'BC-038-1', 'good', 'available'), (76, 38, 'BC-038-2', 'good', 'available'),
(77, 39, 'BC-039-1', 'good', 'available'), (78, 39, 'BC-039-2', 'good', 'available'),
(79, 40, 'BC-040-1', 'good', 'available'), (80, 40, 'BC-040-2', 'good', 'available'),
(81, 41, 'BC-041-1', 'good', 'available'), (82, 41, 'BC-041-2', 'good', 'available'),
(83, 42, 'BC-042-1', 'good', 'available'), (84, 42, 'BC-042-2', 'good', 'available'),
(85, 43, 'BC-043-1', 'good', 'available'), (86, 43, 'BC-043-2', 'good', 'available'),
(87, 44, 'BC-044-1', 'good', 'available'), (88, 44, 'BC-044-2', 'good', 'available'),
(89, 45, 'BC-045-1', 'good', 'available'), (90, 45, 'BC-045-2', 'good', 'available'),
-- Added Books copies (91-150)
(91, 46, 'BC-046-1', 'good', 'available'), (92, 46, 'BC-046-2', 'good', 'available'),
(93, 47, 'BC-047-1', 'good', 'available'), (94, 47, 'BC-047-2', 'good', 'available'),
(95, 48, 'BC-048-1', 'good', 'available'), (96, 48, 'BC-048-2', 'good', 'available'),
(97, 49, 'BC-049-1', 'good', 'available'), (98, 49, 'BC-049-2', 'good', 'available'),
(99, 50, 'BC-050-1', 'good', 'available'), (100, 50, 'BC-050-2', 'good', 'available'),
(101, 51, 'BC-051-1', 'good', 'available'), (102, 51, 'BC-051-2', 'good', 'available'),
(103, 52, 'BC-052-1', 'good', 'available'), (104, 52, 'BC-052-2', 'good', 'available'),
(105, 53, 'BC-053-1', 'good', 'available'), (106, 53, 'BC-053-2', 'good', 'available'),
(107, 54, 'BC-054-1', 'good', 'available'), (108, 54, 'BC-054-2', 'good', 'available'),
(109, 55, 'BC-055-1', 'good', 'available'), (110, 55, 'BC-055-2', 'good', 'available'),
(111, 56, 'BC-056-1', 'good', 'available'), (112, 56, 'BC-056-2', 'good', 'available'),
(113, 57, 'BC-057-1', 'good', 'available'), (114, 57, 'BC-057-2', 'good', 'available'),
(115, 58, 'BC-058-1', 'good', 'available'), (116, 58, 'BC-058-2', 'good', 'available'),
(117, 59, 'BC-059-1', 'good', 'available'), (118, 59, 'BC-059-2', 'good', 'available'),
(119, 60, 'BC-060-1', 'good', 'available'), (120, 60, 'BC-060-2', 'good', 'available'),
(121, 61, 'BC-061-1', 'good', 'available'), (122, 61, 'BC-061-2', 'good', 'available'),
(123, 62, 'BC-062-1', 'good', 'available'), (124, 62, 'BC-062-2', 'good', 'available'),
(125, 63, 'BC-063-1', 'good', 'available'), (126, 63, 'BC-063-2', 'good', 'available'),
(127, 64, 'BC-064-1', 'good', 'available'), (128, 64, 'BC-064-2', 'good', 'available'),
(129, 65, 'BC-065-1', 'good', 'available'), (130, 65, 'BC-065-2', 'good', 'available'),
(131, 66, 'BC-066-1', 'good', 'available'), (132, 66, 'BC-066-2', 'good', 'available'),
(133, 67, 'BC-067-1', 'good', 'available'), (134, 67, 'BC-067-2', 'good', 'available'),
(135, 68, 'BC-068-1', 'good', 'available'), (136, 68, 'BC-068-2', 'good', 'available'),
(137, 69, 'BC-069-1', 'good', 'available'), (138, 69, 'BC-069-2', 'good', 'available'),
(139, 70, 'BC-070-1', 'good', 'available'), (140, 70, 'BC-070-2', 'good', 'available'),
(141, 71, 'BC-071-1', 'good', 'available'), (142, 71, 'BC-071-2', 'good', 'available'),
(143, 72, 'BC-072-1', 'good', 'available'), (144, 72, 'BC-072-2', 'good', 'available'),
(145, 73, 'BC-073-1', 'good', 'available'), (146, 73, 'BC-073-2', 'good', 'available'),
(147, 74, 'BC-074-1', 'good', 'available'), (148, 74, 'BC-074-2', 'good', 'available'),
(149, 75, 'BC-075-1', 'good', 'available'), (150, 75, 'BC-075-2', 'good', 'available');

