-- ==========================================================================
-- LMS SEED DATA SEGMENT: BorrowRecords
-- Auto-generated by splitting tool
-- ==========================================================================

-- ------------------------------------------------------------
-- 8. INSERT BORROW RECORDS (10 BORROW RECORDS PER USER, STRENGTHENED TENDENCIES)
-- ------------------------------------------------------------

-- User 86 (student1@lms.com): Tendency "Java Enterprise Backend & Cloud Native Developer"
INSERT INTO BorrowRecord (borrowRecordId, userId, bookCopyId, bookId, startDate, endDate, returnedAt, status) VALUES
(1, 86, 1, 1, NOW() + INTERVAL '-45 days', NOW() + INTERVAL '-30 days', NOW() + INTERVAL '-31 days', 'returned'),
(2, 86, 3, 2, NOW() + INTERVAL '-40 days', NOW() + INTERVAL '-25 days', NOW() + INTERVAL '-26 days', 'returned'),
(3, 86, 17, 9, NOW() + INTERVAL '-35 days', NOW() + INTERVAL '-20 days', NOW() + INTERVAL '-21 days', 'returned'),
(4, 86, 19, 10, NOW() + INTERVAL '-30 days', NOW() + INTERVAL '-15 days', NOW() + INTERVAL '-16 days', 'returned'),
(5, 86, 21, 11, NOW() + INTERVAL '-25 days', NOW() + INTERVAL '-10 days', NOW() + INTERVAL '-11 days', 'returned'),
(6, 86, 23, 12, NOW() + INTERVAL '-20 days', NOW() + INTERVAL '-5 days', NOW() + INTERVAL '-6 days', 'returned'),
(7, 86, 25, 13, NOW() + INTERVAL '-15 days', NOW() + INTERVAL '-1 days', NOW() + INTERVAL '-2 days', 'returned'),
(8, 86, 33, 17, NOW() + INTERVAL '-10 days', NOW() + INTERVAL '5 days', NULL, 'borrowed'),
(9, 86, 67, 34, NOW() + INTERVAL '-5 days', NOW() + INTERVAL '10 days', NULL, 'borrowed'),
(10, 86, 69, 35, NOW() + INTERVAL '-2 days', NOW() + INTERVAL '13 days', NULL, 'borrowed');

-- User 87 (student2@lms.com): Tendency "Modern Fullstack JavaScript Developer (Node, React, NoSQL)"
INSERT INTO BorrowRecord (borrowRecordId, userId, bookCopyId, bookId, startDate, endDate, returnedAt, status) VALUES
(11, 87, 49, 25, NOW() + INTERVAL '-45 days', NOW() + INTERVAL '-30 days', NOW() + INTERVAL '-31 days', 'returned'),
(12, 87, 51, 26, NOW() + INTERVAL '-40 days', NOW() + INTERVAL '-25 days', NOW() + INTERVAL '-26 days', 'returned'),
(13, 87, 53, 27, NOW() + INTERVAL '-35 days', NOW() + INTERVAL '-20 days', NOW() + INTERVAL '-21 days', 'returned'),
(14, 87, 55, 28, NOW() + INTERVAL '-30 days', NOW() + INTERVAL '-15 days', NOW() + INTERVAL '-16 days', 'returned'),
(15, 87, 57, 29, NOW() + INTERVAL '-25 days', NOW() + INTERVAL '-10 days', NOW() + INTERVAL '-11 days', 'returned'),
(16, 87, 59, 30, NOW() + INTERVAL '-20 days', NOW() + INTERVAL '-5 days', NOW() + INTERVAL '-6 days', 'returned'),
(17, 87, 61, 31, NOW() + INTERVAL '-15 days', NOW() + INTERVAL '-1 days', NOW() + INTERVAL '-2 days', 'returned'),
(18, 87, 63, 32, NOW() + INTERVAL '-10 days', NOW() + INTERVAL '5 days', NULL, 'borrowed'),
(19, 87, 37, 19, NOW() + INTERVAL '-5 days', NOW() + INTERVAL '10 days', NULL, 'borrowed'),
(20, 87, 39, 20, NOW() + INTERVAL '-2 days', NOW() + INTERVAL '13 days', NULL, 'borrowed');

-- User 88 (student3@lms.com): Tendency "AI/ML Engineer & Data Scientist (Python, ML, Data Analytics)"
INSERT INTO BorrowRecord (borrowRecordId, userId, bookCopyId, bookId, startDate, endDate, returnedAt, status) VALUES
(21, 88, 5, 3, NOW() + INTERVAL '-45 days', NOW() + INTERVAL '-30 days', NOW() + INTERVAL '-31 days', 'returned'),
(22, 88, 7, 4, NOW() + INTERVAL '-40 days', NOW() + INTERVAL '-25 days', NOW() + INTERVAL '-26 days', 'returned'),
(23, 88, 79, 40, NOW() + INTERVAL '-35 days', NOW() + INTERVAL '-20 days', NOW() + INTERVAL '-21 days', 'returned'),
(24, 88, 81, 41, NOW() + INTERVAL '-30 days', NOW() + INTERVAL '-15 days', NOW() + INTERVAL '-16 days', 'returned'),
(25, 88, 83, 42, NOW() + INTERVAL '-25 days', NOW() + INTERVAL '-10 days', NOW() + INTERVAL '-11 days', 'returned'),
(26, 88, 85, 43, NOW() + INTERVAL '-20 days', NOW() + INTERVAL '-5 days', NOW() + INTERVAL '-6 days', 'returned'),
(27, 88, 87, 44, NOW() + INTERVAL '-15 days', NOW() + INTERVAL '-1 days', NOW() + INTERVAL '-2 days', 'returned'),
(28, 88, 89, 45, NOW() + INTERVAL '-10 days', NOW() + INTERVAL '5 days', NULL, 'borrowed'),
(29, 88, 41, 21, NOW() + INTERVAL '-5 days', NOW() + INTERVAL '10 days', NULL, 'borrowed'),
(30, 88, 43, 22, NOW() + INTERVAL '-2 days', NOW() + INTERVAL '13 days', NULL, 'borrowed');


