-- ==========================================================================
-- LMS SEED DATA SEGMENT: Categories & Tags (25 Categories, 50 Tags - English)
-- ==========================================================================

-- 1. INSERT CATEGORIES (25 CATEGORIES)
INSERT INTO Category (categoryId, name, description) VALUES 
(1, 'Computer Science', 'Sách khoa học máy tính và công nghệ thông tin'),
(2, 'Engineering', 'Sách kỹ thuật và công nghệ'),
(3, 'Economics & Finance', 'Sách kinh tế học và tài chính'),
(4, 'Business Administration', 'Sách quản trị kinh doanh và marketing'),
(5, 'Medicine & Health Sciences', 'Sách y học và khoa học sức khỏe'),
(6, 'Pharmacy & Biochemistry', 'Sách dược học và hóa sinh'),
(7, 'Law & Legal Studies', 'Sách luật học và pháp lý'),
(8, 'Politics & International Relations', 'Sách chính trị học và quan hệ quốc tế'),
(9, 'Linguistics & Literature', 'Sách ngôn ngữ học và văn học'),
(10, 'Psychology', 'Sách tâm lý học và hành vi'),
(11, 'Education', 'Sách giáo dục học và sư phạm'),
(12, 'Sociology', 'Sách xã hội học và nhân chủng học'),
(13, 'Philosophy', 'Sách triết học và tư tưởng'),
(14, 'History & Archaeology', 'Sách lịch sử và khảo cổ học'),
(15, 'Mathematics & Statistics', 'Sách toán học và thống kê'),
(16, 'Physics', 'Sách vật lý học và thiên văn'),
(17, 'Chemistry', 'Sách hóa học và khoa học vật liệu'),
(18, 'Biology & Ecology', 'Sách sinh học và sinh thái học'),
(19, 'Architecture', 'Sách kiến trúc và quy hoạch đô thị'),
(20, 'Arts & Design', 'Sách mỹ thuật, âm nhạc và thiết kế'),
(21, 'Media & Journalism', 'Sách truyền thông và báo chí'),
(22, 'Environmental Studies', 'Sách môi trường và biến đổi khí hậu'),
(23, 'Agriculture', 'Sách nông nghiệp và công nghệ thực phẩm'),
(24, 'Tourism & Hospitality', 'Sách quản trị du lịch và khách sạn'),
(25, 'Soft Skills', 'Sách kỹ năng mềm và phát triển bản thân');

-- 2. INSERT TAGS (50 TAGS)
INSERT INTO Tag (tagId, name) VALUES 
(1, 'Textbook'),
(2, 'Reference'),
(3, 'LabManual'),
(4, 'Regulations'),
(5, 'Monograph'),
(6, 'Anthology'),
(7, 'Dictionary'),
(8, 'CaseStudy'),
(9, 'Exercises'),
(10, 'Thesis'),
(11, 'Proceedings'),
(12, 'Bilingual'),
(13, 'Introduction'),
(14, 'Advanced'),
(15, 'ExamPrep'),
(16, 'DataAnalysis'),
(17, 'AI_Driven'),
(18, 'DigitalTransformation'),
(19, 'ResearchMethodology'),
(20, 'Experimental'),
(21, 'Theoretical'),
(22, 'Modeling'),
(23, 'Statistical'),
(24, 'Coding'),
(25, 'Visual_Design'),
(26, 'Strategic'),
(27, 'Management'),
(28, 'Auditing_Assessment'),
(29, 'Security_Safety'),
(30, 'InformationSystems'),
(31, 'Automation'),
(32, 'Survey_Data'),
(33, 'OpenSource'),
(34, 'Simulation'),
(35, 'Optimization'),
(36, 'Sustainability'),
(37, 'Ethics'),
(38, 'Globalization'),
(39, 'PublicPolicy'),
(40, 'Startup'),
(41, 'GreenEconomy'),
(42, 'CrossCultural'),
(43, 'HistoryOf'),
(44, 'FutureTrends'),
(45, 'AppliedSciences'),
(46, 'EmergingTech'),
(47, 'BigData'),
(48, 'Urbanization'),
(49, 'Behavioral'),
(50, 'NicheTopic');
