@startuml ForgotPasswordFlow
skinparam activity {
  BackgroundColor White
  BorderColor Black
  DiamondBackgroundColor White
  DiamondBorderColor Black
}
skinparam ArrowColor Black
skinparam titleBorderThickness 1
skinparam titleBorderColor Black
skinparam titleBackgroundColor White
title Forgot Password Flow

|User|
start
:Request password reset with email;

|System|
:Verify email & process reset request;

fork
  :Return reset request acknowledgement;
  |User|
  :Receive reset response notice;
  |System|
fork again
  |Email System|
  :Send email with temporary password;
  |System|
end fork

|User|
:Submit temporary password\n& new password;

|System|
:Validate reset credentials & update password;

if (Reset credentials & new password valid?) then (No)
  :Display password reset error;
  |User|
  :View error message;
  |System|
else (Yes)
  |User|
  :View success notice & proceed to login;
  |System|
endif

|System|
stop
@enduml
