-- ============================================================
-- LIBRARY MANAGEMENT SYSTEM — POSTGRESQL SCHEMA FOR SUPABASE
-- ============================================================

-- ============================================================
-- MÚI GIỜ — BẮT BUỘC CHẠY KHI DỰNG DATABASE MỚI
-- ============================================================
-- Các cột thời gian dùng kiểu TIMESTAMP (không kèm time zone) và được ghi bằng NOW().
-- Giá trị lưu xuống phụ thuộc vào múi giờ của session, nên múi giờ PHẢI được đặt ở cấp
-- database. Nếu bỏ qua bước này, toàn bộ mốc thời gian sẽ lệch 7 tiếng so với giờ Việt Nam.
--
-- Ứng dụng KHÔNG tự đặt múi giờ nữa vì hai cách phía client đều không dùng được:
--   1. "SET TIME ZONE" mỗi lần lấy connection: tốn thêm một vòng mạng (~39ms) và không
--      đáng tin ở chế độ transaction pooling của Supavisor (cổng 6543).
--   2. Tham số "options=-c timezone=..." trong chuỗi kết nối: bị Supavisor bỏ qua
--      (đã kiểm chứng — ép options=UTC nhưng session vẫn giữ Asia/Ho_Chi_Minh).
--
-- Chạy lệnh dưới đây một lần, bằng tài khoản sở hữu database, rồi mở lại kết nối:
--
--     ALTER DATABASE postgres SET timezone TO 'Asia/Ho_Chi_Minh';
--
-- Kiểm tra lại bằng: SHOW TIME ZONE;   -- kỳ vọng: Asia/Ho_Chi_Minh
-- (Lệnh để ở dạng ghi chú vì tên database có thể khác và ALTER DATABASE đòi quyền sở hữu.)

-- ============================================================
-- XÓA BẢNG NẾU ĐÃ TỒN TẠI (Theo thứ tự ngược lại để không lỗi khóa ngoại)
-- ============================================================
DROP TABLE IF EXISTS SuggestionVote CASCADE;
DROP TABLE IF EXISTS BookSuggestion CASCADE;
DROP TABLE IF EXISTS InventoryItem CASCADE;
DROP TABLE IF EXISTS InventorySession CASCADE;
DROP TABLE IF EXISTS BookImportError CASCADE;
DROP TABLE IF EXISTS BookImportBatch CASCADE;
DROP TABLE IF EXISTS BookCopyIncident CASCADE;
DROP TABLE IF EXISTS EmailTemplate CASCADE;
DROP TABLE IF EXISTS DocumentTemp CASCADE;
DROP TABLE IF EXISTS UserNotificationStatus CASCADE;
DROP TABLE IF EXISTS Notification CASCADE;
DROP TABLE IF EXISTS Payment CASCADE;
DROP TABLE IF EXISTS Fine CASCADE;
DROP TABLE IF EXISTS BorrowRecord CASCADE;
DROP TABLE IF EXISTS Reservation CASCADE;
DROP TABLE IF EXISTS BookCopy CASCADE;
DROP TABLE IF EXISTS BookTag CASCADE;
DROP TABLE IF EXISTS BookCategory CASCADE;
DROP TABLE IF EXISTS Book CASCADE;
DROP TABLE IF EXISTS Tag CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS AuditLogs CASCADE;
DROP TABLE IF EXISTS SystemConfigurations CASCADE;
DROP TABLE IF EXISTS Admin CASCADE;
DROP TABLE IF EXISTS Librarian CASCADE;
DROP TABLE IF EXISTS Lecturer CASCADE;
DROP TABLE IF EXISTS Student CASCADE;
DROP TABLE IF EXISTS MemberProfile CASCADE;
DROP TABLE IF EXISTS UserLockReason CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

-- 1. Bảng User
CREATE TABLE "User" (
    userId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    passwordHash VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    role VARCHAR(50) NOT NULL,
    failedLoginAttempts INT NOT NULL DEFAULT 0,
    lockedUntil TIMESTAMP NULL
);

-- 2. Bảng UserLockReason
CREATE TABLE UserLockReason (
    lockReasonId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId INT NOT NULL,
    reason VARCHAR(50) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_UserLockReason_User FOREIGN KEY (userId) 
        REFERENCES "User"(userId) 
        ON DELETE CASCADE
);

-- 3. Bảng MemberProfile
CREATE TABLE MemberProfile (
    userId INT PRIMARY KEY,
    fullName VARCHAR(255) NOT NULL,
    phoneNumber VARCHAR(20) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    dateOfBirth DATE NOT NULL,
    startDate DATE NULL,
    endDate DATE NULL,
    CONSTRAINT FK_MemberProfile_User FOREIGN KEY (userId) REFERENCES "User"(userId) ON DELETE CASCADE
);

-- 4. Bảng Student
CREATE TABLE Student (
    userId INT PRIMARY KEY,
    studentCode VARCHAR(50) NOT NULL UNIQUE,
    major VARCHAR(255) NULL,
    enrollmentYear INT NULL,
    CONSTRAINT FK_Student_User FOREIGN KEY (userId) REFERENCES "User"(userId) ON DELETE CASCADE
);

-- 5. Bảng Lecturer
CREATE TABLE Lecturer (
    userId INT PRIMARY KEY,
    lecturerCode VARCHAR(50) NOT NULL UNIQUE,
    department VARCHAR(255) NULL,
    CONSTRAINT FK_Lecturer_User FOREIGN KEY (userId) REFERENCES "User"(userId) ON DELETE CASCADE
);

-- 6. Bảng Librarian
CREATE TABLE Librarian (
    userId INT PRIMARY KEY,
    staffCode VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT FK_Librarian_User FOREIGN KEY (userId) REFERENCES "User"(userId) ON DELETE CASCADE
);


-- 8. Bảng Admin
CREATE TABLE Admin (
    userId INT PRIMARY KEY,
    staffCode VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT FK_Admin_User FOREIGN KEY (userId) REFERENCES "User"(userId) ON DELETE CASCADE
);

-- 9. Bảng SystemConfigurations
CREATE TABLE SystemConfigurations (
    configKey VARCHAR(100) PRIMARY KEY,
    configValue TEXT NULL,
    description TEXT NULL,
    configGroup VARCHAR(50) NOT NULL DEFAULT 'system',
    updatedBy INT NULL,
    updatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_SystemConfigurations_User FOREIGN KEY (updatedBy) REFERENCES "User"(userId)
);

-- 10. Bảng AuditLogs
CREATE TABLE AuditLogs (
    auditLogId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId INT NULL,
    actionType VARCHAR(100) NOT NULL,
    entityName VARCHAR(255) NULL,
    entityId INT NULL,
    oldValues TEXT NULL,
    newValues TEXT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_AuditLogs_User FOREIGN KEY (userId) REFERENCES "User"(userId)
);

-- 11. Bảng Category
CREATE TABLE Category (
    categoryId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    updatedAt TIMESTAMP NULL DEFAULT NOW(),
    updatedBy INT NULL,
    CONSTRAINT CK_Category_Status CHECK (status IN ('active', 'inactive', 'hidden')),
    CONSTRAINT FK_Category_UpdatedBy FOREIGN KEY (updatedBy) REFERENCES "User"(userId)
);

-- 12. Bảng Tag
CREATE TABLE Tag (
    tagId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    updatedAt TIMESTAMP NULL DEFAULT NOW(),
    updatedBy INT NULL,
    CONSTRAINT CK_Tag_Status CHECK (status IN ('active', 'inactive', 'hidden')),
    CONSTRAINT FK_Tag_UpdatedBy FOREIGN KEY (updatedBy) REFERENCES "User"(userId)
);

-- 13. Bảng Book
CREATE TABLE Book (
    bookId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(20) NOT NULL UNIQUE,
    title VARCHAR(500) NOT NULL,
    author VARCHAR(500) NULL,
    publisher VARCHAR(255) NULL,
    publicationYear INT NULL,
    price DECIMAL(18,2) NULL CHECK (price IS NULL OR price >= 0),
    imagePath VARCHAR(255) NULL,
    totalQuantity INT NOT NULL DEFAULT 0 CHECK (totalQuantity >= 0),
    availableQuantity INT NOT NULL DEFAULT 0 CHECK (availableQuantity >= 0),
    status VARCHAR(50) NOT NULL DEFAULT 'available',
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    updatedAt TIMESTAMP NULL,
    CONSTRAINT CK_Book_AvailableQuantity_Lte_TotalQuantity CHECK (availableQuantity <= totalQuantity),
    CONSTRAINT CK_Book_Status CHECK (status IN ('available', 'unavailable'))
);

-- 14. Bảng BookCategory
CREATE TABLE BookCategory (
    bookId INT NOT NULL,
    categoryId INT NOT NULL,
    PRIMARY KEY (bookId, categoryId),
    CONSTRAINT FK_BookCategory_Book FOREIGN KEY (bookId) REFERENCES Book(bookId) ON DELETE CASCADE,
    CONSTRAINT FK_BookCategory_Category FOREIGN KEY (categoryId) REFERENCES Category(categoryId) ON DELETE CASCADE
);

-- 15. Bảng BookTag
CREATE TABLE BookTag (
    bookId INT NOT NULL,
    tagId INT NOT NULL,
    PRIMARY KEY (bookId, tagId),
    CONSTRAINT FK_BookTag_Book FOREIGN KEY (bookId) REFERENCES Book(bookId) ON DELETE CASCADE,
    CONSTRAINT FK_BookTag_Tag FOREIGN KEY (tagId) REFERENCES Tag(tagId) ON DELETE CASCADE
);

-- 16. Bảng BookCopy
CREATE TABLE BookCopy (
    bookCopyId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookId INT NOT NULL,
    location VARCHAR(255) NULL,
    condition VARCHAR(100) NOT NULL DEFAULT 'good',
    status VARCHAR(50) NOT NULL DEFAULT 'available',
    barcode VARCHAR(50) NOT NULL UNIQUE,
    removedFromInventory BOOLEAN NOT NULL DEFAULT FALSE,
    removedFromInventoryAt TIMESTAMP NULL,
    removedFromInventoryBy INT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    updatedAt TIMESTAMP NULL,
    CONSTRAINT CK_BookCopy_Condition CHECK (condition IN ('good', 'damaged', 'lost')),
    CONSTRAINT CK_BookCopy_Status CHECK (status IN ('available', 'unavailable', 'borrowed', 'reserved')),
    CONSTRAINT CK_BookCopy_RemovedInventory CHECK (
        removedFromInventory = FALSE
        OR (status = 'unavailable' AND condition IN ('damaged', 'lost') AND removedFromInventoryAt IS NOT NULL)
    ),
    CONSTRAINT FK_BookCopy_RemovedBy FOREIGN KEY (removedFromInventoryBy) REFERENCES "User"(userId),
    CONSTRAINT FK_BookCopy_Book FOREIGN KEY (bookId) REFERENCES Book(bookId) ON DELETE CASCADE
);

-- 17. Bảng Reservation
CREATE TABLE Reservation (
    reservationId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId INT NOT NULL,
    bookId INT NOT NULL,
    bookCopyId INT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    queuePosition INT NULL,
    startDate TIMESTAMP NULL DEFAULT NOW(),
    endDate TIMESTAMP NULL,
    CONSTRAINT FK_Reservation_User FOREIGN KEY (userId) REFERENCES "User"(userId),
    CONSTRAINT FK_Reservation_Book FOREIGN KEY (bookId) REFERENCES Book(bookId),
    CONSTRAINT FK_Reservation_BookCopy FOREIGN KEY (bookCopyId) REFERENCES BookCopy(bookCopyId)
);

-- 18. Bảng BorrowRecord
CREATE TABLE BorrowRecord (
    borrowRecordId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId INT NOT NULL,
    bookCopyId INT NOT NULL,
    bookId INT NOT NULL,
    startDate TIMESTAMP NOT NULL DEFAULT NOW(),
    endDate TIMESTAMP NOT NULL,
    returnedAt TIMESTAMP NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'borrowed',
    extensionCount INT NOT NULL DEFAULT 0,
    createdBy INT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_BorrowRecord_User FOREIGN KEY (userId) REFERENCES "User"(userId),
    CONSTRAINT FK_BorrowRecord_BookCopy FOREIGN KEY (bookCopyId) REFERENCES BookCopy(bookCopyId),
    CONSTRAINT FK_BorrowRecord_Book FOREIGN KEY (bookId) REFERENCES Book(bookId),
    CONSTRAINT FK_BorrowRecord_CreatedBy FOREIGN KEY (createdBy) REFERENCES "User"(userId)
);

-- 19. Bảng Fine
CREATE TABLE Fine (
    fineId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrowRecordId INT NOT NULL,
    userId INT NOT NULL,
    amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    reason VARCHAR(500) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'unpaid',
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_Fine_BorrowRecord FOREIGN KEY (borrowRecordId) REFERENCES BorrowRecord(borrowRecordId),
    CONSTRAINT FK_Fine_User FOREIGN KEY (userId) REFERENCES "User"(userId)
);

-- 20. Bảng Payment
CREATE TABLE Payment (
    paymentId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fineId INT NOT NULL,
    paidAmount DECIMAL(18,2) NOT NULL,
    paymentMethod VARCHAR(100) NULL,
    transactionReference VARCHAR(255) NULL UNIQUE,
    processedBy INT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    paidAt TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_Payment_Fine FOREIGN KEY (fineId) REFERENCES Fine(fineId),
    CONSTRAINT FK_Payment_ProcessedBy FOREIGN KEY (processedBy) REFERENCES "User"(userId)
);

-- 21. Bảng Notification
CREATE TABLE Notification (
    notificationId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    content TEXT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'general',
    targetRole VARCHAR(50) DEFAULT 'ALL',
    isPinned BOOLEAN NOT NULL DEFAULT FALSE,
    thumbnailUrl VARCHAR(500) NULL,
    createdBy INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    updatedAt TIMESTAMP NULL,
    CONSTRAINT FK_Notification_User FOREIGN KEY (createdBy) REFERENCES "User"(userId)
);

-- 22. Bảng UserNotificationStatus
CREATE TABLE UserNotificationStatus (
    userId INT NOT NULL,
    notificationId INT NOT NULL,
    readAt TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (userId, notificationId),
    CONSTRAINT FK_UNS_User FOREIGN KEY (userId) REFERENCES "User"(userId) ON DELETE CASCADE,
    CONSTRAINT FK_UNS_Notification FOREIGN KEY (notificationId) REFERENCES Notification(notificationId) ON DELETE CASCADE
);

-- 23. Bảng DocumentTemp
CREATE TABLE DocumentTemp (
    tempId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tempName VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500) NULL,
    subject VARCHAR(255) NOT NULL,
    bodyContent TEXT NOT NULL,
    managerId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    updatedAt TIMESTAMP NULL,
    CONSTRAINT FK_DocumentTemp_User FOREIGN KEY (managerId) REFERENCES "User"(userId)
);

-- 23b. Bảng EmailTemplate (Mẫu Email Hệ Thống cho tiến trình ngầm Async Email Sender)
CREATE TABLE EmailTemplate (
    templateId  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tempName    VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500) NULL,
    subject     VARCHAR(255) NOT NULL,
    bodyContent TEXT NOT NULL,
    updatedBy   INT NULL,
    updatedAt   TIMESTAMP NULL,
    CONSTRAINT FK_EmailTemplate_User FOREIGN KEY (updatedBy) REFERENCES "User"(userId)
);

-- 24. Bảng BookCopyIncident
CREATE TABLE BookCopyIncident (
    incidentId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookCopyId INT NOT NULL,
    incidentType VARCHAR(20) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    resolution VARCHAR(1000) NULL,
    reportedBy INT NOT NULL,
    reportedAt TIMESTAMP NOT NULL DEFAULT NOW(),
    resolvedBy INT NULL,
    resolvedAt TIMESTAMP NULL,
    CONSTRAINT FK_BookCopyIncident_BookCopy FOREIGN KEY (bookCopyId) REFERENCES BookCopy(bookCopyId) ON DELETE CASCADE,
    CONSTRAINT FK_BookCopyIncident_ReportedBy FOREIGN KEY (reportedBy) REFERENCES "User"(userId),
    CONSTRAINT FK_BookCopyIncident_ResolvedBy FOREIGN KEY (resolvedBy) REFERENCES "User"(userId),
    CONSTRAINT CK_BookCopyIncident_Type CHECK (incidentType IN ('damaged', 'lost')),
    CONSTRAINT CK_BookCopyIncident_Status CHECK (status IN ('pending', 'investigating', 'resolved', 'rejected'))
);

-- 25. Bảng BookImportBatch
CREATE TABLE BookImportBatch (
    importBatchId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    importedBy INT NOT NULL,
    fileName VARCHAR(255) NOT NULL,
    totalRows INT NOT NULL DEFAULT 0 CHECK (totalRows >= 0),
    successRows INT NOT NULL DEFAULT 0 CHECK (successRows >= 0),
    failedRows INT NOT NULL DEFAULT 0 CHECK (failedRows >= 0),
    status VARCHAR(50) NOT NULL DEFAULT 'failed',
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    expiresAt TIMESTAMP NOT NULL DEFAULT (NOW() + INTERVAL '1 year'),
    CONSTRAINT FK_BookImportBatch_ImportedBy FOREIGN KEY (importedBy) REFERENCES "User"(userId),
    CONSTRAINT CK_BookImportBatch_RowCounts CHECK (successRows + failedRows <= totalRows),
    CONSTRAINT CK_BookImportBatch_Status CHECK (status IN ('success', 'failed'))
);

-- 26. Bảng BookImportError
CREATE TABLE BookImportError (
    importErrorId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    importBatchId INT NOT NULL,
    sheetName VARCHAR(50) NOT NULL,
    rowNumber INT NOT NULL CHECK (rowNumber >= 1),
    columnName VARCHAR(100) NULL,
    errorMessage VARCHAR(1000) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_BookImportError_Batch FOREIGN KEY (importBatchId)
        REFERENCES BookImportBatch(importBatchId) ON DELETE CASCADE,
    CONSTRAINT CK_BookImportError_SheetName CHECK (sheetName IN ('Books', 'BookCopies'))
);

-- 27. Bảng InventorySession
CREATE TABLE InventorySession (
    inventorySessionId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    startedBy INT NOT NULL,
    startedAt TIMESTAMP NOT NULL DEFAULT NOW(),
    completedBy INT NULL,
    completedAt TIMESTAMP NULL,
    note VARCHAR(1000) NULL,
    CONSTRAINT FK_InventorySession_StartedBy FOREIGN KEY (startedBy) REFERENCES "User"(userId),
    CONSTRAINT FK_InventorySession_CompletedBy FOREIGN KEY (completedBy) REFERENCES "User"(userId),
    CONSTRAINT CK_InventorySession_Status CHECK (status IN ('draft', 'counting', 'reviewing', 'completed', 'cancelled'))
);

-- 28. Bảng InventoryItem
CREATE TABLE InventoryItem (
    inventoryItemId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventorySessionId INT NOT NULL,
    bookCopyId INT NOT NULL,
    expectedLocation VARCHAR(255) NOT NULL,
    scannedLocation VARCHAR(255) NULL,
    result VARCHAR(20) NOT NULL DEFAULT 'pending',
    scannedBy INT NULL,
    scannedAt TIMESTAMP NULL,
    resolution VARCHAR(1000) NULL,
    resolvedBy INT NULL,
    resolvedAt TIMESTAMP NULL,
    CONSTRAINT FK_InventoryItem_Session FOREIGN KEY (inventorySessionId)
        REFERENCES InventorySession(inventorySessionId) ON DELETE CASCADE,
    CONSTRAINT FK_InventoryItem_BookCopy FOREIGN KEY (bookCopyId) REFERENCES BookCopy(bookCopyId) ON DELETE CASCADE,
    CONSTRAINT FK_InventoryItem_ScannedBy FOREIGN KEY (scannedBy) REFERENCES "User"(userId),
    CONSTRAINT FK_InventoryItem_ResolvedBy FOREIGN KEY (resolvedBy) REFERENCES "User"(userId),
    CONSTRAINT CK_InventoryItem_Result CHECK (result IN ('pending', 'matched', 'missing', 'misplaced'))
);

-- Indexes
CREATE UNIQUE INDEX IF NOT EXISTS UX_BookCopyIncident_Open ON BookCopyIncident(bookCopyId)
    WHERE status <> 'resolved' AND status <> 'rejected';

CREATE INDEX IF NOT EXISTS IX_BookCopyIncident_Status_ReportedAt ON BookCopyIncident(status, reportedAt DESC);

CREATE INDEX IF NOT EXISTS IX_BookImportBatch_CreatedAt ON BookImportBatch(createdAt);

CREATE UNIQUE INDEX IF NOT EXISTS UX_InventoryItem_Session_Copy ON InventoryItem(inventorySessionId, bookCopyId);

CREATE INDEX IF NOT EXISTS IX_InventorySession_StartedAt ON InventorySession(startedAt DESC);

-- 29. Bảng BookSuggestion
CREATE TABLE BookSuggestion (
    suggestionId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    publisher VARCHAR(255) NULL,
    isbn VARCHAR(20) NULL,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    voteCount INT NOT NULL DEFAULT 1 CHECK (voteCount >= 0),
    librarianNote TEXT NULL,
    createdBy INT NOT NULL,
    reviewedBy INT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    updatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_BookSuggestion_CreatedBy FOREIGN KEY (createdBy) REFERENCES "User"(userId),
    CONSTRAINT FK_BookSuggestion_ReviewedBy FOREIGN KEY (reviewedBy) REFERENCES "User"(userId),
    CONSTRAINT CK_BookSuggestion_Status CHECK (status IN ('pending', 'acknowledged', 'rejected'))
);

-- 30. Bảng SuggestionVote
CREATE TABLE SuggestionVote (
    voteId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suggestionId INT NOT NULL,
    userId INT NOT NULL,
    votedAt TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_SuggestionVote_Suggestion FOREIGN KEY (suggestionId) REFERENCES BookSuggestion(suggestionId) ON DELETE CASCADE,
    CONSTRAINT FK_SuggestionVote_User FOREIGN KEY (userId) REFERENCES "User"(userId),
    CONSTRAINT UX_SuggestionVote_User_Suggestion UNIQUE (suggestionId, userId)
);

-- Indexes for performance SLA (< 200ms)
CREATE INDEX IF NOT EXISTS IX_BookSuggestion_Status_VoteCount ON BookSuggestion(status, voteCount DESC, createdAt ASC);
CREATE INDEX IF NOT EXISTS IX_BookSuggestion_Title ON BookSuggestion(title);
