<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html><html lang="vi"><jsp:include page="fragments/_head.jsp" /><body class="d-flex flex-column"><jsp:include page="fragments/_sidebar.jsp" /><div class="d-flex main-wrapper overflow-hidden"><main class="flex-grow-1 overflow-y-auto main-content-layout"><jsp:include page="fragments/_header.jsp" />
<div class="container-fluid px-4 py-4 bm-page">
<c:if test="${not empty sessionScope.successMessage}"><div class="alert alert-success alert-dismissible fade show"><c:out value="${sessionScope.successMessage}"/><button class="btn-close" data-bs-dismiss="alert"></button></div><c:remove var="successMessage" scope="session"/></c:if>
<c:if test="${not empty sessionScope.errorMessage}"><div class="alert alert-danger alert-dismissible fade show"><c:out value="${sessionScope.errorMessage}"/><button class="btn-close" data-bs-dismiss="alert"></button></div><c:remove var="errorMessage" scope="session"/></c:if>
<section class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="bm-page__eyebrow mb-1">Kho vật lý</p><h2 class="bm-page__title mb-1">Đối chiếu tồn kho</h2><p class="bm-page__subtitle mb-0">Quét mã vạch theo khu vực, xác minh chênh lệch trước khi cập nhật kho.</p></div><c:if test="${canEdit}"><button class="btn btn-primary-custom" data-bs-toggle="modal" data-bs-target="#createInventoryModal"><span class="material-symbols-outlined">add</span>Tạo phiên kiểm kê</button></c:if></section>
<div class="bm-list-stats bm-list-stats--four mb-3">
<article class="bm-list-stat"><span class="material-symbols-outlined">fact_check</span><div><p class="bm-stat-card__label mb-1">Tổng phiên</p><p class="bm-stat-card__value mb-0">${summary.totalSessions}</p></div></article>
<article class="bm-list-stat bm-list-stat--info"><span class="material-symbols-outlined">barcode_scanner</span><div><p class="bm-stat-card__label mb-1">Đang kiểm đếm</p><p class="bm-stat-card__value mb-0">${summary.activeSessions}</p></div></article>
<article class="bm-list-stat bm-list-stat--warning"><span class="material-symbols-outlined">manage_search</span><div><p class="bm-stat-card__label mb-1">Chờ xác minh</p><p class="bm-stat-card__value mb-0">${summary.reviewingSessions}</p></div></article>
<article class="bm-list-stat bm-list-stat--danger"><span class="material-symbols-outlined">warning</span><div><p class="bm-stat-card__label mb-1">Lệch chưa xử lý</p><p class="bm-stat-card__value mb-0">${summary.unresolvedItems}</p></div></article>
</div>
<c:choose><c:when test="${not empty selectedSession}">
<section class="bm-side-card mb-3 d-flex flex-wrap justify-content-between gap-3"><div><a class="bm-action-link" href="${pageContext.request.contextPath}/book-management/inventory">← Danh sách phiên</a><h3 class="bm-section-title mt-2 mb-1">Phiên #${selectedSession.inventorySessionId} · <c:out value="${selectedSession.location}"/></h3><p class="bm-section-note mb-0">Dự kiến ${selectedSession.expectedCount} · Khớp ${selectedSession.matchedCount} · Chênh lệch ${selectedSession.discrepancyCount}</p></div><div class="bm-actions"><c:if test="${canEdit and selectedSession.status == 'draft'}"><form method="post"><input type="hidden" name="action" value="start"><input type="hidden" name="sessionId" value="${selectedSession.inventorySessionId}"><button class="btn btn-primary-custom">Bắt đầu kiểm đếm</button></form></c:if><c:if test="${canEdit and selectedSession.status == 'counting'}"><form method="post"><input type="hidden" name="action" value="finish-counting"><input type="hidden" name="sessionId" value="${selectedSession.inventorySessionId}"><button class="btn btn-primary-custom">Kết thúc quét</button></form></c:if><c:if test="${canEdit and selectedSession.status == 'reviewing' and selectedSession.unresolvedCount == 0}"><form method="post"><input type="hidden" name="action" value="complete"><input type="hidden" name="sessionId" value="${selectedSession.inventorySessionId}"><button class="btn btn-primary-custom">Hoàn tất phiên</button></form></c:if><c:if test="${canEdit and selectedSession.status != 'completed' and selectedSession.status != 'cancelled'}"><form method="post"><input type="hidden" name="action" value="cancel"><input type="hidden" name="sessionId" value="${selectedSession.inventorySessionId}"><button class="btn bm-btn-secondary">Hủy phiên</button></form></c:if></div></section>
<c:if test="${canEdit and selectedSession.status == 'counting'}"><form class="bm-filter-card bm-list-filter mb-3" method="post"><input type="hidden" name="action" value="scan"><input type="hidden" name="sessionId" value="${selectedSession.inventorySessionId}"><div class="row g-2"><div class="col-lg-10 bm-search"><span class="material-symbols-outlined">barcode_scanner</span><input class="form-control" name="barcode" autofocus required placeholder="Quét hoặc nhập mã vạch"></div><div class="col-lg-2"><button class="btn btn-primary-custom w-100 h-100">Ghi nhận</button></div></div></form></c:if>
<section class="bm-table-card bm-table-card--primary bm-data-table"><div class="table-responsive"><table class="table table-lms"><thead><tr><th>Mã vạch / đầu sách</th><th>Vị trí hệ thống</th><th>Vị trí quét</th><th>Kết quả</th><th>Kết luận</th><th></th></tr></thead><tbody>
<c:forEach var="item" items="${items}"><tr><td><strong><c:out value="${item.barcode}"/></strong><div class="bm-book__meta"><c:out value="${item.bookTitle}"/></div></td><td><c:out value="${item.expectedLocation}"/></td><td><c:out value="${empty item.scannedLocation ? 'Chưa quét' : item.scannedLocation}"/></td><td><c:choose><c:when test="${item.result=='matched'}"><span class="bm-badge bm-badge--success">Khớp</span></c:when><c:when test="${item.result=='missing'}"><span class="bm-badge bm-badge--danger">Thiếu</span></c:when><c:when test="${item.result=='misplaced'}"><span class="bm-badge bm-badge--warning">Sai vị trí</span></c:when><c:otherwise><span class="bm-badge bm-badge--neutral">Chưa quét</span></c:otherwise></c:choose></td><td><c:out value="${empty item.resolution ? 'Chưa xử lý' : item.resolution}"/></td><td><c:if test="${canEdit and selectedSession.status=='reviewing' and empty item.resolvedAt and item.result=='misplaced'}"><form method="post"><input type="hidden" name="action" value="resolve-misplaced"><input type="hidden" name="sessionId" value="${selectedSession.inventorySessionId}"><input type="hidden" name="itemId" value="${item.inventoryItemId}"><button class="btn btn-sm bm-btn-secondary">Cập nhật vị trí</button></form></c:if><c:if test="${canEdit and selectedSession.status=='reviewing' and empty item.resolvedAt and item.result=='missing'}"><form method="post"><input type="hidden" name="action" value="resolve-missing"><input type="hidden" name="sessionId" value="${selectedSession.inventorySessionId}"><input type="hidden" name="itemId" value="${item.inventoryItemId}"><button class="btn btn-sm bm-incident-button">Ghi nhận mất</button></form></c:if></td></tr></c:forEach>
<c:if test="${empty items}"><tr><td colspan="6"><div class="bm-empty-state"><span class="material-symbols-outlined">inventory</span><strong>Không có bản sao trong phiên</strong><span>Khu vực này chưa có bản sao phù hợp.</span></div></td></tr></c:if></tbody></table></div></section>
</c:when><c:otherwise>
<section class="bm-table-card bm-table-card--primary bm-data-table"><div class="table-responsive"><table class="table table-lms"><thead><tr><th>Phiên / khu vực</th><th>Người tạo</th><th>Bắt đầu</th><th>Dự kiến</th><th>Khớp</th><th>Chênh lệch</th><th>Trạng thái</th><th></th></tr></thead><tbody><c:forEach var="item" items="${sessions}"><tr><td><strong>#${item.inventorySessionId} · <c:out value="${item.location}"/></strong></td><td><c:out value="${item.startedByName}"/></td><td><fmt:formatDate value="${item.startedAt}" pattern="dd/MM/yyyy HH:mm"/></td><td>${item.expectedCount}</td><td>${item.matchedCount}</td><td>${item.discrepancyCount}</td><td><c:choose><c:when test="${item.status=='completed'}"><span class="bm-badge bm-badge--success">Đã hoàn tất</span></c:when><c:when test="${item.status=='reviewing'}"><span class="bm-badge bm-badge--warning">Chờ xác minh</span></c:when><c:when test="${item.status=='counting'}"><span class="bm-badge bm-badge--info">Đang kiểm đếm</span></c:when><c:when test="${item.status=='cancelled'}"><span class="bm-badge bm-badge--neutral">Đã hủy</span></c:when><c:otherwise><span class="bm-badge bm-badge--neutral">Bản nháp</span></c:otherwise></c:choose></td><td><a class="btn btn-sm bm-btn-secondary" href="${pageContext.request.contextPath}/book-management/inventory?sessionId=${item.inventorySessionId}">Chi tiết</a></td></tr></c:forEach><c:if test="${empty sessions}"><tr><td colspan="8"><div class="bm-empty-state"><span class="material-symbols-outlined">fact_check</span><strong>Chưa có phiên kiểm kê</strong><span>Tạo phiên đầu tiên để bắt đầu đối chiếu.</span></div></td></tr></c:if></tbody></table></div></section>
</c:otherwise></c:choose></div><jsp:include page="fragments/_footer.jsp" /></main></div>
<c:if test="${canEdit}"><div class="modal fade bm-modal" id="createInventoryModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post" action="${pageContext.request.contextPath}/book-management/inventory"><input type="hidden" name="action" value="create"><div class="modal-header"><h5 class="modal-title">Tạo phiên kiểm kê</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Khu vực kiểm kê</label><select class="form-select" name="location" required><option value="">Chọn khu vực</option><c:forEach var="location" items="${locations}"><option value="<c:out value="${location}"/>"><c:out value="${location}"/></option></c:forEach></select></div><div><label class="form-label">Ghi chú</label><textarea class="form-control" name="note" maxlength="1000"></textarea></div></div><div class="modal-footer"><button type="button" class="btn bm-btn-secondary" data-bs-dismiss="modal">Hủy</button><button class="btn btn-primary-custom">Tạo phiên</button></div></form></div></div></div></c:if>
</body></html>
