<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html><html lang="vi"><jsp:include page="fragments/_head.jsp" /><body class="d-flex flex-column"><jsp:include page="fragments/_sidebar.jsp" /><div class="d-flex main-wrapper overflow-hidden"><main class="flex-grow-1 overflow-y-auto main-content-layout"><jsp:include page="fragments/_header.jsp" />
<div class="container-fluid px-4 py-4 bm-page"><section class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="bm-page__eyebrow mb-1">Kho vật lý</p><h2 class="bm-page__title mb-1">Tất cả bản sao</h2><p class="bm-page__subtitle mb-0">Theo dõi từng cuốn sách vật lý theo mã vạch, vị trí và trạng thái lưu thông.</p></div><button class="btn btn-primary-custom" data-bs-toggle="modal" data-bs-target="#copyModal"><span class="material-symbols-outlined">add</span> Thêm bản sao</button></section>
<section class="bm-filter-card mb-3"><div class="row g-2"><div class="col-lg-4 bm-search"><span class="material-symbols-outlined">barcode_scanner</span><input class="form-control" placeholder="Quét mã vạch hoặc tìm tên sách"></div><div class="col-md-3"><select class="form-select"><option>Tất cả vị trí</option><option>Kho A - Kệ A12</option><option>Kho B - Kệ B04</option></select></div><div class="col-md-3"><select class="form-select"><option>Mọi trạng thái</option><option>Sẵn sàng</option><option>Đang mượn</option><option>Đặt trước</option><option>Hỏng hoặc mất</option></select></div><div class="col-md-2"><div class="bm-filter-actions"><button class="btn bm-filter-button flex-grow-1" type="button"><span class="material-symbols-outlined">filter_alt</span><span>Lọc kho</span></button><button class="btn bm-reset-button" type="button" title="Đặt lại bộ lọc" aria-label="Đặt lại bộ lọc"><span class="material-symbols-outlined">refresh</span></button></div></div></div></section>
<div class="bm-rule-note mb-3"><strong>Quy tắc:</strong> Không thể sửa tình trạng vật lý của bản sao đang được mượn hoặc đã được đặt trước.</div>
<div class="bm-summary-strip mb-3"><span class="bm-summary-strip__item">Tổng: <strong>35.921</strong></span><span class="bm-summary-strip__item">Sẵn sàng: <strong>26.361</strong></span><span class="bm-summary-strip__item">Đang mượn: <strong>8.914</strong></span><span class="bm-summary-strip__item">Hỏng/mất: <strong>646</strong></span></div>
<section class="bm-table-card"><div class="table-responsive"><table class="table table-lms"><thead><tr><th>Mã vạch</th><th>Đầu sách</th><th>Vị trí</th><th>Tình trạng</th><th>Lưu thông</th><th>Cập nhật</th><th></th></tr></thead><tbody>
<tr><td><strong>BC-00018291</strong></td><td>Lập trình Java căn bản</td><td>Kho A · Kệ A12</td><td><span class="bm-badge bm-badge--success">Tốt</span></td><td><span class="bm-badge bm-badge--success">Sẵn sàng</span></td><td>09/06/2026</td><td><button class="btn btn-sm bm-btn-secondary">Cập nhật</button></td></tr>
<tr><td><strong>BC-00018292</strong></td><td>Lập trình Java căn bản</td><td>Kho A · Kệ A12</td><td><span class="bm-badge bm-badge--warning">Mòn nhẹ</span></td><td><span class="bm-badge bm-badge--info">Đang mượn</span></td><td>07/06/2026</td><td><button class="btn btn-sm bm-btn-secondary">Chỉ xem</button></td></tr>
<tr><td><strong>BC-00026312</strong></td><td>Cơ sở dữ liệu hiện đại</td><td>Kho B · Kệ B04</td><td><span class="bm-badge bm-badge--danger">Hỏng</span></td><td><span class="bm-badge bm-badge--neutral">Ngừng lưu thông</span></td><td>08/06/2026</td><td><a class="btn btn-sm bm-incident-button" href="book-damaged-lost.jsp">Xử lý sự cố</a></td></tr>
</tbody></table></div></section></div><jsp:include page="fragments/_footer.jsp" /></main></div>
<div class="modal fade bm-modal" id="copyModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Thêm bản sao vật lý</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Đầu sách</label><select class="form-select mb-3"><option>Chọn đầu sách</option></select><label class="form-label">Mã vạch</label><input class="form-control mb-3" placeholder="Ví dụ: BC-00018293"><label class="form-label">Vị trí</label><select class="form-select"><option>Chọn kho và kệ</option></select></div><div class="modal-footer"><button class="btn bm-btn-secondary" data-bs-dismiss="modal">Hủy</button><button class="btn btn-primary-custom">Lưu bản sao</button></div></div></div></div>
</body></html>
