<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html><html lang="vi"><jsp:include page="fragments/_head.jsp" /><body class="d-flex flex-column"><jsp:include page="fragments/_sidebar.jsp" />
<div class="d-flex main-wrapper overflow-hidden"><main class="flex-grow-1 overflow-y-auto main-content-layout"><jsp:include page="fragments/_header.jsp" />
<div class="container-fluid px-4 py-4 bm-page">
<section class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="bm-page__eyebrow mb-1">Danh mục sách</p><h2 class="bm-page__title mb-1">Đầu sách</h2><p class="bm-page__subtitle mb-0">Quản lý thông tin thư mục; số lượng bản sao được quản lý riêng tại kho vật lý.</p></div><button class="btn btn-primary-custom" data-bs-toggle="modal" data-bs-target="#titleModal"><span class="material-symbols-outlined">add</span> Tạo đầu sách</button></section>
<section class="bm-filter-card mb-3"><div class="row g-2"><div class="col-lg-5 bm-search"><span class="material-symbols-outlined">search</span><input class="form-control" placeholder="Tìm theo tên sách, ISBN hoặc tác giả"></div><div class="col-md-3"><select class="form-select"><option>Tất cả thể loại</option><option>Công nghệ thông tin</option><option>Kinh tế</option></select></div><div class="col-md-2"><select class="form-select"><option>Mọi trạng thái</option><option>Đang sử dụng</option><option>Ngừng sử dụng</option></select></div><div class="col-md-2"><button class="btn bm-btn-secondary w-100">Lọc danh sách</button></div></div></section>
<div class="bm-summary-strip mb-3"><span class="bm-summary-strip__item">Tổng cộng: <strong>12.480 đầu sách</strong></span><span class="bm-summary-strip__item">Có bản sao: <strong>11.928</strong></span><span class="bm-summary-strip__item">Chưa có bản sao: <strong>552</strong></span></div>
<section class="bm-table-card"><div class="table-responsive"><table class="table table-lms"><thead><tr><th>Đầu sách</th><th>ISBN</th><th>Thể loại &amp; thẻ</th><th>Xuất bản</th><th>Bản sao</th><th>Trạng thái</th><th></th></tr></thead><tbody>
<tr><td><div class="bm-book"><span class="bm-book__cover material-symbols-outlined">menu_book</span><div><p class="bm-book__title mb-1">Lập trình Java căn bản</p><p class="bm-book__meta mb-0">Nguyễn Văn An</p></div></div></td><td>978-604-01-1234-5</td><td><span class="bm-tag">CNTT</span> <span class="bm-tag">Java</span></td><td>NXB Giáo dục, 2024</td><td><strong>24</strong></td><td><span class="bm-badge bm-badge--success">Đang sử dụng</span></td><td><button class="btn btn-sm bm-btn-secondary">Chi tiết</button></td></tr>
<tr><td><div class="bm-book"><span class="bm-book__cover material-symbols-outlined">menu_book</span><div><p class="bm-book__title mb-1">Cơ sở dữ liệu hiện đại</p><p class="bm-book__meta mb-0">Trần Minh Tú</p></div></div></td><td>978-604-02-3921-1</td><td><span class="bm-tag">CNTT</span> <span class="bm-tag">SQL</span></td><td>NXB Khoa học, 2023</td><td><strong>18</strong></td><td><span class="bm-badge bm-badge--success">Đang sử dụng</span></td><td><button class="btn btn-sm bm-btn-secondary">Chi tiết</button></td></tr>
<tr><td><div class="bm-book"><span class="bm-book__cover material-symbols-outlined">menu_book</span><div><p class="bm-book__title mb-1">Quản trị học nhập môn</p><p class="bm-book__meta mb-0">Lê Hoàng Nam</p></div></div></td><td>978-604-03-8842-4</td><td><span class="bm-tag">Kinh tế</span></td><td>NXB Lao động, 2018</td><td><strong>0</strong></td><td><span class="bm-badge bm-badge--neutral">Chưa có bản sao</span></td><td><button class="btn btn-sm bm-btn-secondary">Chi tiết</button></td></tr>
</tbody></table></div></section>
</div><jsp:include page="fragments/_footer.jsp" /></main></div>
<div class="modal fade bm-modal" id="titleModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><div><h5 class="modal-title">Tạo đầu sách</h5><p class="bm-section-note mb-0">Chỉ tạo thông tin thư mục, chưa tạo bản sao vật lý.</p></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label">Tên sách</label><input class="form-control"></div><div class="col-md-6"><label class="form-label">ISBN</label><input class="form-control"></div><div class="col-md-6"><label class="form-label">Tác giả</label><input class="form-control"></div><div class="col-md-6"><label class="form-label">Thể loại</label><select class="form-select"><option>Chọn thể loại</option></select></div><div class="col-md-6"><label class="form-label">Nhà xuất bản</label><input class="form-control"></div></div></div><div class="modal-footer"><button class="btn bm-btn-secondary" data-bs-dismiss="modal">Hủy</button><button class="btn btn-primary-custom">Lưu đầu sách</button></div></div></div></div>
</body></html>
