<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html><html lang="vi"><jsp:include page="fragments/_head.jsp" /><body class="d-flex flex-column"><jsp:include page="fragments/_sidebar.jsp" /><div class="d-flex main-wrapper overflow-hidden"><main class="flex-grow-1 overflow-y-auto main-content-layout"><jsp:include page="fragments/_header.jsp" />
<div class="container-fluid px-4 py-4 bm-page"><section class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="bm-page__eyebrow mb-1">Kho vật lý</p><h2 class="bm-page__title mb-1">Đối chiếu tồn kho</h2><p class="bm-page__subtitle mb-0">So sánh số liệu hệ thống với kết quả kiểm kê thực tế, không tự động sửa dữ liệu.</p></div><button class="btn btn-primary-custom"><span class="material-symbols-outlined">sync</span> Làm mới đối chiếu</button></section>
<div class="bm-rule-note mb-3"><strong>Lưu ý kiểm soát:</strong> Chênh lệch chỉ tạo cảnh báo để thủ thư xác minh. Mọi điều chỉnh bản sao phải được thực hiện tại màn hình kho và ghi nhật ký.</div>
<section class="bm-filter-card mb-3"><div class="row g-2"><div class="col-md-4"><select class="form-select"><option>Tất cả khu vực kho</option><option>Kho A - Giáo trình</option><option>Kho B - Tham khảo</option></select></div><div class="col-md-3"><input class="form-control" type="date"></div><div class="col-md-3"><select class="form-select"><option>Chỉ hiển thị có lệch</option><option>Hiển thị tất cả</option></select></div><div class="col-md-2"><button class="btn bm-btn-secondary w-100">Áp dụng</button></div></div></section>
<section class="bm-table-card"><div class="bm-table-card__header"><h3 class="bm-section-title mb-1">Kết quả kiểm kê ngày 09/06/2026</h3><p class="bm-section-note mb-0">5 đầu sách có chênh lệch, cần xác minh 7 bản sao.</p></div><div class="table-responsive"><table class="table table-lms"><thead><tr><th>Đầu sách</th><th>Vị trí</th><th>Hệ thống</th><th>Thực tế</th><th>Chênh lệch</th><th>Trạng thái</th><th></th></tr></thead><tbody>
<tr><td><strong>Lập trình Java căn bản</strong><br><span class="bm-empty-note">ISBN 978-604-01-1234-5</span></td><td>Kho A · Kệ A12</td><td>24</td><td>23</td><td><span class="bm-delta bm-delta--negative">-1</span></td><td><span class="bm-badge bm-badge--warning">Chờ xác minh</span></td><td><button class="btn btn-sm btn-primary-custom">Xác minh</button></td></tr>
<tr><td><strong>Kinh tế vi mô</strong><br><span class="bm-empty-note">ISBN 978-604-08-8871-2</span></td><td>Kho B · Kệ B04</td><td>16</td><td>18</td><td><span class="bm-delta bm-delta--positive">+2</span></td><td><span class="bm-badge bm-badge--info">Đang xác minh</span></td><td><button class="btn btn-sm bm-btn-secondary">Chi tiết</button></td></tr>
<tr><td><strong>Cơ sở dữ liệu hiện đại</strong><br><span class="bm-empty-note">ISBN 978-604-02-3921-1</span></td><td>Kho A · Kệ A18</td><td>18</td><td>18</td><td><span class="bm-delta">0</span></td><td><span class="bm-badge bm-badge--success">Khớp</span></td><td><button class="btn btn-sm bm-btn-secondary">Chi tiết</button></td></tr>
</tbody></table></div></section></div><jsp:include page="fragments/_footer.jsp" /></main></div></body></html>
