<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html><html lang="vi"><jsp:include page="fragments/_head.jsp" /><body class="d-flex flex-column"><jsp:include page="fragments/_sidebar.jsp" /><div class="d-flex main-wrapper overflow-hidden"><main class="flex-grow-1 overflow-y-auto main-content-layout"><jsp:include page="fragments/_header.jsp" />
<div class="container-fluid px-4 py-4 bm-page"><section class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="bm-page__eyebrow mb-1">Kho vật lý</p><h2 class="bm-page__title mb-1">Hỏng &amp; mất</h2><p class="bm-page__subtitle mb-0">Hàng đợi xác minh và xử lý các bản sao không còn đủ điều kiện lưu thông.</p></div><button class="btn btn-primary-custom" data-bs-toggle="modal" data-bs-target="#reportModal"><span class="material-symbols-outlined">add</span> Ghi nhận sự cố</button></section>
<div class="row g-3 mb-3"><div class="col-md-4"><article class="raised-card p-3"><p class="bm-stat-card__label mb-1">Chờ xác minh</p><p class="bm-stat-card__value mb-0">8</p></article></div><div class="col-md-4"><article class="raised-card p-3"><p class="bm-stat-card__label mb-1">Đang xử lý</p><p class="bm-stat-card__value mb-0">14</p></article></div><div class="col-md-4"><article class="raised-card p-3"><p class="bm-stat-card__label mb-1">Đã xử lý tháng này</p><p class="bm-stat-card__value mb-0">31</p></article></div></div>
<section class="bm-filter-card mb-3"><div class="row g-2"><div class="col-lg-5 bm-search"><span class="material-symbols-outlined">search</span><input class="form-control" placeholder="Tìm mã vạch hoặc đầu sách"></div><div class="col-md-3"><select class="form-select"><option>Tất cả loại sự cố</option><option>Hỏng</option><option>Mất</option></select></div><div class="col-md-2"><select class="form-select"><option>Mọi trạng thái</option><option>Chờ xác minh</option><option>Đang xử lý</option><option>Đã xử lý</option></select></div><div class="col-md-2"><div class="bm-filter-actions"><button class="btn bm-filter-button flex-grow-1" type="button"><span class="material-symbols-outlined">filter_alt</span><span>Lọc</span></button><button class="btn bm-reset-button" type="button" title="Đặt lại bộ lọc" aria-label="Đặt lại bộ lọc"><span class="material-symbols-outlined">refresh</span></button></div></div></div></section>
<section class="bm-table-card"><div class="table-responsive"><table class="table table-lms"><thead><tr><th>Bản sao</th><th>Sự cố</th><th>Ghi nhận</th><th>Người báo</th><th>Trạng thái</th><th>Hướng xử lý</th><th></th></tr></thead><tbody>
<tr><td><strong>BC-00026312</strong><br>Cơ sở dữ liệu hiện đại</td><td><span class="bm-badge bm-badge--danger">Hỏng</span><br><span class="bm-empty-note">Rách gáy, thiếu trang 42</span></td><td>08/06/2026</td><td>Nguyễn Thị Lan</td><td><span class="bm-badge bm-badge--warning">Chờ xác minh</span></td><td>Chưa quyết định</td><td><button class="btn btn-sm btn-primary-custom">Xử lý</button></td></tr>
<tr><td><strong>BC-00017302</strong><br>Kinh tế vi mô</td><td><span class="bm-badge bm-badge--danger">Mất</span><br><span class="bm-empty-note">Không tìm thấy sau kiểm kê</span></td><td>05/06/2026</td><td>Trần Hoàng Minh</td><td><span class="bm-badge bm-badge--info">Đang xử lý</span></td><td>Chờ kết luận kiểm kê</td><td><button class="btn btn-sm bm-btn-secondary">Chi tiết</button></td></tr>
<tr><td><strong>BC-00009124</strong><br>Quản trị học nhập môn</td><td><span class="bm-badge bm-badge--danger">Hỏng</span><br><span class="bm-empty-note">Ngấm nước</span></td><td>01/06/2026</td><td>Nguyễn Thị Lan</td><td><span class="bm-badge bm-badge--success">Đã xử lý</span></td><td>Ngừng lưu thông</td><td><button class="btn btn-sm bm-btn-secondary">Chi tiết</button></td></tr>
</tbody></table></div></section></div><jsp:include page="fragments/_footer.jsp" /></main></div>
<div class="modal fade bm-modal" id="reportModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Ghi nhận sự cố bản sao</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Mã vạch</label><input class="form-control mb-3" placeholder="Quét hoặc nhập mã vạch"><label class="form-label">Loại sự cố</label><select class="form-select mb-3"><option>Hỏng</option><option>Mất</option></select><label class="form-label">Mô tả hiện trạng</label><textarea class="form-control" rows="3"></textarea></div><div class="modal-footer"><button class="btn bm-btn-secondary" data-bs-dismiss="modal">Hủy</button><button class="btn btn-primary-custom">Ghi nhận</button></div></div></div></div>
</body></html>
