<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html><html lang="vi"><jsp:include page="fragments/_head.jsp" /><body class="d-flex flex-column"><jsp:include page="fragments/_sidebar.jsp" /><div class="d-flex main-wrapper overflow-hidden"><main class="flex-grow-1 overflow-y-auto main-content-layout"><jsp:include page="fragments/_header.jsp" />
<div class="container-fluid px-4 py-4 bm-page"><section class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="bm-page__eyebrow mb-1">Import &amp; lịch sử</p><h2 class="bm-page__title mb-1">Lịch sử xử lý</h2><p class="bm-page__subtitle mb-0">Theo dõi kết quả, người thực hiện và lỗi của từng phiên import sách.</p></div><a class="btn btn-primary-custom" href="book-import.jsp"><span class="material-symbols-outlined">upload_file</span> Import mới</a></section>
<section class="bm-filter-card mb-3"><div class="row g-2"><div class="col-lg-4 bm-search"><span class="material-symbols-outlined">search</span><input class="form-control" placeholder="Tìm mã phiên hoặc tên tệp"></div><div class="col-md-3"><select class="form-select"><option>Mọi kết quả</option><option>Thành công</option><option>Thất bại</option><option>Đang xử lý</option></select></div><div class="col-md-3"><input class="form-control" type="date"></div><div class="col-md-2"><button class="btn bm-btn-secondary w-100">Lọc</button></div></div></section>
<section class="bm-table-card"><div class="table-responsive"><table class="table table-lms"><thead><tr><th>Mã phiên</th><th>Tệp dữ liệu</th><th>Người thực hiện</th><th>Thời gian</th><th>Kết quả</th><th>Đầu sách / bản sao</th><th></th></tr></thead><tbody>
<tr><td><strong>IMP-20260609-003</strong></td><td>sach_hoc_ky_3.xlsx<br><span class="bm-empty-note">1,2 MB · 320 dòng</span></td><td>Nguyễn Thị Lan</td><td>09/06/2026 09:12</td><td><span class="bm-badge bm-badge--success">Thành công</span></td><td>286 / 842</td><td><button class="btn btn-sm bm-btn-secondary" data-bs-toggle="modal" data-bs-target="#historyModal">Chi tiết</button></td></tr>
<tr><td><strong>IMP-20260608-011</strong></td><td>bo_sung_giao_trinh.xlsx<br><span class="bm-empty-note">840 KB · 180 dòng</span></td><td>Trần Hoàng Minh</td><td>08/06/2026 15:30</td><td><span class="bm-badge bm-badge--danger">Thất bại</span></td><td>0 / 0</td><td><button class="btn btn-sm bm-btn-secondary" data-bs-toggle="modal" data-bs-target="#historyModal">Xem lỗi</button></td></tr>
<tr><td><strong>IMP-20260608-004</strong></td><td>sach_tham_khao.xlsx<br><span class="bm-empty-note">2,1 MB · 760 dòng</span></td><td>Nguyễn Thị Lan</td><td>08/06/2026 08:45</td><td><span class="bm-badge bm-badge--success">Thành công</span></td><td>704 / 1.926</td><td><button class="btn btn-sm bm-btn-secondary" data-bs-toggle="modal" data-bs-target="#historyModal">Chi tiết</button></td></tr>
</tbody></table></div></section></div><jsp:include page="fragments/_footer.jsp" /></main></div>
<div class="modal fade bm-modal" id="historyModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><div><h5 class="modal-title">Chi tiết phiên IMP-20260608-011</h5><p class="bm-section-note mb-0">Phiên đã hoàn tác, không có dữ liệu nào được lưu.</p></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="bm-summary-strip mb-3"><span class="bm-summary-strip__item">Tổng dòng: <strong>180</strong></span><span class="bm-summary-strip__item">Hợp lệ: <strong>177</strong></span><span class="bm-summary-strip__item">Có lỗi: <strong>3</strong></span></div><table class="table table-lms"><thead><tr><th>Dòng</th><th>Cột</th><th>Nội dung lỗi</th></tr></thead><tbody><tr><td>24</td><td>ISBN</td><td>ISBN đã tồn tại nhưng thông tin đầu sách không khớp.</td></tr><tr><td>81</td><td>Mã vạch</td><td>Mã vạch trùng với bản sao hiện có.</td></tr><tr><td>114</td><td>Thể loại</td><td>Không tìm thấy thể loại được chỉ định.</td></tr></tbody></table></div><div class="modal-footer"><button class="btn bm-btn-secondary">Tải báo cáo lỗi</button><button class="btn btn-primary-custom" data-bs-dismiss="modal">Đóng</button></div></div></div></div>
</body></html>
